[package]
name = "linux-app-editor"
version = "0.1.0"
description = "A small Linux desktop-entry creator/editor for manually installed applications"
authors = ["lihaozhe"]
edition = "2024"

[workspace]
members = [".", "crates/systemd-service-core", "crates/systemd-service-tui"]
default-members = ["."]
resolver = "3"

[lib]
name = "linux_app_editor_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2.0.21"
tempfile = "3.27.0"
which = "8.0.6"
backhand = "0.25"
memchr = "2"
systemd-service-core = { path = "crates/systemd-service-core" }
