[package]
name = "systemd-service-tui"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "systemd-service-editor"
path = "src/main.rs"

[dependencies]
systemd-service-core = { path = "../systemd-service-core" }
ratatui = "0.30.2"
ratatui-textarea = "0.9.2"
crossterm = "0.29"
unicode-width = "0.2"

[dev-dependencies]
tempfile = "3"
